# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='createdon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trips',
            name='leavingon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trips',
            name='modifiedon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trips',
            name='reachingon',
            field=models.IntegerField(),
        ),
    ]
