# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20180326_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='trustee',
        ),
    ]
