# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_remove_trips_trustee'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='timezone',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
