# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-12 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_auto_20180512_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='timezone',
            new_name='timezoneoffset',
        ),
    ]
